---
title: "Uma propriedade interessante envolvendo números transcendentais"
description: "Como mostrar que e^pi > pi^e ?"
date: 2025-05-21
categories: [Matemática]
format:
  html:
    toc: true
    code-fold: true
---

### Como podemos mostrar que $e^\pi > \pi^e ?$ 

Esses dias eu estava com um pouco de tempo livre e vendo algumas atualizações no instagram. Eu curto muito páginas que dedicam publicações relacionadas à matemática e estatística.
Vi uma afirmação bem intrigante: será que $e^\pi > \pi^e$ ? 

Existem algumas maneiras de provar isso, e a que mais me pareceu razoável e mais 
tranquila de resolver foi considerar a expensão em série de Taylor da função $\exp(x)$ que é bastante conhecida: 

$$
e^x = 1 + \frac{x}{1!} + \frac{x^2}{2!} + \frac{x^3}{3!} + \ldots
$$

Aqui temos que a exponencial é decomposta em soma de infinitos termos e podemos certamente afirmar que se $\exp(x) = 1 + x + (\text{infinitos termos})$, claramente vale que 

$$
e^x > 1 + x
$$

Então, se fizermos especificamente (finja que tirei esse valor por puro talento matemático rsrs) $x = \frac{\pi}{e} - 1$, então pela relação acima temos: 

$$
e^{\pi/e - 1} > 1 + \frac{\pi}{e} - 1 
$$

Isso implica que: 

$$
e^{\pi/e - 1} > \frac{\pi}{e} 
$$

Aqui parece meio confuso, mas vamos reorganizar isso tudo: 

$$
e^{\pi/e} e^{-1} > \pi e^{-1} \implies e^{\pi/e} > \pi
$$

Aqui vem o "pulo do gato": elevar ambos os lados pelo número de euler ($e$): 

$$
(e^{\pi/e})^e > \pi^e \implies e^\pi > \pi^e 
$$

O que conclui a demonstração !

Esse resultado é muito bonito, pois envolve desigualdade de números transcendentais como $\pi$ e $e$. Provamos então que a desigualdade é válida. 

### Outras considerações

Poderíamos partir da análise da seguinte função: 

$$
f(x) = \frac{x}{e} - \ln(x). 
$$

Podemos estudar algumas propriedades através da primeira derivada da função: 

$$
f'(x) = \frac{1}{e} - \frac{1}{x} 
$$

> Lembre-se que a derivada da função $\ln(x) = 1/x$. 

Para $x = e$ temos que $f'(x) = 0$. Para saber se esse ponto é ponto de máximo local (ou mínimo local) calculamos a segunda derivada da função: 

$$
f''(x) = 1/x^2
$$

e para $x = e$ , $f''(e) = 1/e^2 > 0$ (mínimo local). Logo, temos que $x = e$ é ponto de mínimo local. Agora analisemos o caso em que $x > e$. Para esse caso 
temos $f'(x) > 0$ ($1/e > 1/x$). Concluímos que 

1. $f(e) = 0$
2. $f(x) > 0, \forall x > e$

Como $\pi > e$, segue que 

$$
f(\pi)  = \frac{\pi}{e} - \ln(\pi) > 0 
$$

e isto nos traz que $\pi / e > \ln(\pi)$. A partir daqui podemos fazer: 


$$
\begin{align*}
\pi &> e \ln(\pi) \\
e^\pi &> e^{e \ln(\pi)} \\ 
e^\pi &> e^{\ln(\pi^e)} \\ 
e^\pi &> \pi^e
\end{align*}
$$

o que prova o resultado ! 

### Outra maneira bastante elegante

Considere o teorema do valor médio para integrais: 

**Teorema**: se $f:[a,b] \rightarrow \mathbb{R}$ é contínua, existe $c$ tal que: 

$$
f(c) = \int_{a}^{b} f(x) dx = f(c)(b-a). 
$$

Utilizando o teorema, vamos considerar $f(x) = 1/x$, $a=e$ e $b=\pi$. Pelo teorema acima temos que existe $c$ tal que 

$$
f(c) = \int_{e}^{\pi} \frac{1}{x} dx = \frac{1}{c}(\pi-e), 
$$

e particularmente para $c > e$ temos 

$$
\frac{1}{c}(\pi-e) < \frac{1}{e}(\pi-e)
$$

Assim calculamos a integral 

$$
\int_{e}^{\pi} \frac{1}{x} dx = \ln(\pi) - \ln(e) < \frac{1}{e}(\pi - e)
$$

Veja que $ln(e) = 1$ então temos

\begin{align}
\ln(\pi) - 1 &< \frac{\pi}{e} - 1 \\ 
\ln(\pi) &< \frac{\pi}{e} \\ 
e^{\ln(\pi)} &< e^{\pi/e} \\ 
\pi &< e^{\pi/e} \\ 
\pi^{e} &< e^{\pi}
\end{align}

provando assim o resultado desejado. Elegante, não ? 

### Como prova o teorema do valor médio para integrais ? 

Aqui usamos dois teoremas: 

1. Teorema do Valor Extremo 
2. Teorema do Valor Intermediário

**Teorema do Valor Extremo**: Seja $f$ contínua em um intervalo fechado e limitado $[a,b]$, então: 

- $f$ atinge um **mínimo absoluto**
- $f$ atinge um **máximo absoluto**

Ou seja, existem pontos $x_m$ e $x_M$ $\in [a,b]$ tais que 

$$
f(x_m) \leq f(x) \leq f(x_M)
$$

para todo $x \in [a,b]$. 

**Teorema do Valor Intermediário (TVI)**: Se $f$ é contínua em $[a,b]$ e $y$ é um ponto entre $f(a)$ e $f(b)$ então existe 
$c \in [a,b]$ tal que $f(c) = y$.  

---

Agora vamos demonstrar o teorema do valor médio para integrais. Pelo Teorema do Valor Extremo existem $m = \text{min}_{[a,b]} f(x)$ e $M = \text{max}_{[a,b]} f(x)$. 
Para todo $x \in [a,b]$ vale que 

$$
m \leq f(x) \leq M. 
$$

Integrando todos os membros dessa desigualdade no intervalo $[a,b]$ temos 

$$
\int_{a}^{b} m \, dx \leq \int_{a}^{b} f(x) dx \leq \int_{a}^{b} M \, dx 
$$

Como $m$ e $M$ são constantes, temos 

$$
m(b-a) \leq \int_{a}^{b} f(x) dx \leq M(b-a) 
$$

Dividindo todos os mebros por $b-a > 0$ temos 

$$
m \leq \frac{1}{b-a}\int_{a}^{b} f(x) dx \leq M 
$$

Seja 

$$
A = \frac{1}{b-a}\int_{a}^{b} f(x) dx, 
$$

temos que $A \in [m,M]$. Usando o fato de $f$ ser contínua, quando aplicamos a função a qualquer valor em $[a,b]$ temos valores entre $[m,M]$, isto é,
a imagem de $f$ é todo o intervalo $[m,M]$. Aqui podemos afirmar que se $A \in [m,M]$ então existe $c \in [a,b]$ tal que $f(c) = A$ (pelo TVI), ou seja, 

$$
f(c) = \frac{1}{b-a}\int_{a}^{b} f(x) dx. 
$$

Multilicando por $b-a$: 

$$
\int_{a}^{b} f(x) dx = f(c)(b-a).   
$$